version: "3.8"
services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-pipeline-api}"
    image: localstack/localstack:3.8
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      DEBUG: ${DEBUG:-0}
      AWS_DEFAULT_REGION: eu-west-2
      SERVICES: sqs, s3
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./localstack/volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./localstack/bootstrap:/etc/localstack/init/ready.d/"

  pipeline-api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GIT_COMMIT: placeholder
    environment:
      PYTHONUNBUFFERED: 1
      AWS_ENDPOINT_URL: http://localstack:4566
      CELERY_BROKER_URL: sqs://ABCDEFGHIJKLMNOPQRST:ZYXK7NiynGlTogH8Nj+P9nlE73sq3@localstack:4566
      AWS_DEFAULT_REGION: eu-west-2
      AWS_ACCESS_KEY_ID: example
      AWS_SECRET_ACCESS_KEY: example
      SQS_QUEUE_NAME: request-queue
      DATABASE_URL: postgresql://postgres:password@request-db/request_database
      SENTRY_ENABLED: "false"
      SENTRY_DSN: https://secret.sentry.url/here
      SENTRY_ENVIRONMENT: docker-compose-local
      SENTRY_TRACING_ENABLED: "true"
      SENTRY_TRACING_SAMPLE_RATE: "0.50"
      SENTRY_DEBUG: "true"
    restart: on-failure
    ports:
      - "8000:8000"